### ISSUE TITLE
User Role Routes

### ISSUE THREAD

**Issue by PatrickBrown1** [TritonSE/MAW-Volunteer-Hub#51]
Create the following routes:
1. Set user roles. The request body should contain a roles object. This object will look like the following:
```
{
    "Wish Granter": true,
    "Volunteer": true,
    "Mentor": false,
    ...
}
```
It must include every single role specified below. If not, it is a malformed request. Set the user's role list to include exactly every single one of the roles that was specified to be true, and none of the roles that were specified as false.
2. Get users by role: returns a list of users that have a specific role 
These are the allowed roles:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/29768212/154776743-4dc61f2b-b6e5-4d0c-8600-95545d7ba841.png">

**Comment by mohakvni** [comment]
#63
